/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: jspurlin (https://sketchfab.com/jspurlin)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/computer-desk-51bf8a73694141c99b801d64f5b2960a
title: Computer Desk
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'
import ComputerDeskModelPath from './computerDesk.glb'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
  }
  materials: {
    Computer: THREE.MeshStandardMaterial
    Desk: THREE.MeshStandardMaterial
    Keyboard: THREE.MeshStandardMaterial
  }
}

const ComputerDesk = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(ComputerDeskModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group
        scale={7}
        position={[315, -206, -2278]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Computer}
        />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Desk} />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Keyboard}
        />
      </group>
    </group>
  )
}

export default ComputerDesk
