/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: KOMODOZ (https://sketchfab.com/komodoz)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/workshop-table-industrial-18b392ae42994abaa76dbbd7804c3514
title: Workshop table industrial
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import TableModelPath from './table.glb'
import { useGLTF } from '@react-three/drei'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001_metal_0: THREE.Mesh
    Cylinder002_metal_0: THREE.Mesh
    Cylinder005_metal_0: THREE.Mesh
    Box001_wood_0: THREE.Mesh
    Cylinder004_metal_0: THREE.Mesh
    Cylinder003_metal_0: THREE.Mesh
    Cylinder006_metal_0: THREE.Mesh
    Cylinder007_metal_0: THREE.Mesh
    Cylinder008_metal_0: THREE.Mesh
    Cylinder009_metal_0: THREE.Mesh
    Cylinder010_metal_0: THREE.Mesh
    Cylinder011_metal_0: THREE.Mesh
    Cylinder012_metal_0: THREE.Mesh
    Cylinder013_metal_0: THREE.Mesh
    Cylinder014_metal_0: THREE.Mesh
    Cylinder015_metal_0: THREE.Mesh
    Cylinder016_metal_0: THREE.Mesh
    Cylinder017_metal_0: THREE.Mesh
    Cylinder018_metal_0: THREE.Mesh
    Cylinder019_metal_0: THREE.Mesh
    Cylinder020_metal_0: THREE.Mesh
    Cylinder021_metal_0: THREE.Mesh
    Cylinder022_metal_0: THREE.Mesh
    Cylinder023_metal_0: THREE.Mesh
    Cylinder024_metal_0: THREE.Mesh
    Cylinder025_metal_0: THREE.Mesh
    Cylinder026_metal_0: THREE.Mesh
    Cylinder027_metal_0: THREE.Mesh
  }
  materials: {
    metal: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
  }
}

const Table = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(TableModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={10}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[59.65, 0, 30.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Cylinder001_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group position={[59.65, 0, 30.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Cylinder002_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[59.65, 49.46, 30.02]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder005_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group position={[0, 50, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Box001_wood_0.geometry}
              material={materials.wood}
            />
          </group>
          <group
            position={[59.65, 13.76, 26.88]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder004_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[59.65, 11.28, 30.02]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder003_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group position={[-59.65, 0, 30.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Cylinder006_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[-59.65, 49.46, 30.02]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder007_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[-59.65, 11.28, 30.02]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder008_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[-59.65, 13.76, 26.88]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder009_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group position={[-59.65, 0, 30.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Cylinder010_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group position={[59.65, 0, -30.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Cylinder011_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group position={[59.65, 0, -30.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Cylinder012_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[59.65, 49.46, -30.02]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder013_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[-59.65, 13.76, -26.88]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder014_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[59.65, 13.76, -26.88]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder015_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[59.65, 11.28, -30.02]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder016_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group position={[-59.65, 0, -30.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Cylinder017_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[-59.65, 49.46, -30.02]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder018_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[-59.65, 11.28, -30.02]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder019_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group position={[-59.65, 0, -30.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Cylinder020_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[59.65, 13.76, -29.84]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder021_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[-59.65, 13.76, -29.84]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder022_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group position={[-60.07, 13.76, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Cylinder023_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[-59.64, 13.76, 2.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder024_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[-56.5, 13.76, -0.06]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder025_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[59.64, 13.76, 2.43]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder026_metal_0.geometry}
              material={materials.metal}
            />
          </group>
          <group
            position={[56.5, 13.76, -0.06]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Cylinder027_metal_0.geometry}
              material={materials.metal}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

export default Table
