/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: filththemutt (https://sketchfab.com/filththemutt)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/projector-screen-low-poly-ad904b77975c44a98a4c33d78a1d5c2b
title: Projector Screen (Low Poly)
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'
import ProjectorScreenModelPath from './projectorScreen.glb'

type GLTFResult = GLTF & {
  nodes: {
    ['Main_Bar_Aluminum_-_Satin_0']: THREE.Mesh
    ['Bottom_Bar_Aluminum_-_Satin_0']: THREE.Mesh
    String_PEEK_0: THREE.Mesh
    ['Ring_Coating_-_Black_Oxide_0']: THREE.Mesh
    ['End_Cap_1_Coating_-_Black_Oxide_0']: THREE.Mesh
    ['End_Cap_2_Coating_-_Black_Oxide_0']: THREE.Mesh
    ['Screen_Rilsan_Invent_Natural_-_PA_11_0']: THREE.Mesh
    ['Hook_Hold_1_Coating_-_Black_Oxide_0']: THREE.Mesh
    ['Hook_Hold_2_Coating_-_Black_Oxide_0']: THREE.Mesh
    ['Hook_1_Brass_-_Polished_0']: THREE.Mesh
    ['Hook_2_Brass_-_Polished_0']: THREE.Mesh
  }
  materials: {
    ['Aluminum_-_Satin']: THREE.MeshStandardMaterial
    PEEK: THREE.MeshStandardMaterial
    ['Coating_-_Black_Oxide']: THREE.MeshStandardMaterial
    ['Rilsan_Invent_Natural_-_PA_11']: THREE.MeshStandardMaterial
    ['Brass_-_Polished']: THREE.MeshStandardMaterial
  }
}

const ProjectorScreen = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(ProjectorScreenModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group
        scale={11}
        position={[0, 1373, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={nodes['Main_Bar_Aluminum_-_Satin_0'].geometry}
          material={materials['Aluminum_-_Satin']}
        />
        <mesh
          geometry={nodes['Bottom_Bar_Aluminum_-_Satin_0'].geometry}
          material={materials['Aluminum_-_Satin']}
        />
        <mesh
          geometry={nodes.String_PEEK_0.geometry}
          material={materials.PEEK}
        />
        <mesh
          geometry={nodes['Ring_Coating_-_Black_Oxide_0'].geometry}
          material={materials['Coating_-_Black_Oxide']}
        />
        <mesh
          geometry={nodes['End_Cap_1_Coating_-_Black_Oxide_0'].geometry}
          material={materials['Coating_-_Black_Oxide']}
        />
        <mesh
          geometry={nodes['End_Cap_2_Coating_-_Black_Oxide_0'].geometry}
          material={materials['Coating_-_Black_Oxide']}
        />
        <mesh
          geometry={nodes['Screen_Rilsan_Invent_Natural_-_PA_11_0'].geometry}
          material={materials['Rilsan_Invent_Natural_-_PA_11']}
        />
        <mesh
          geometry={nodes['Hook_Hold_1_Coating_-_Black_Oxide_0'].geometry}
          material={materials['Coating_-_Black_Oxide']}
        />
        <mesh
          geometry={nodes['Hook_Hold_2_Coating_-_Black_Oxide_0'].geometry}
          material={materials['Coating_-_Black_Oxide']}
        />
        <mesh
          geometry={nodes['Hook_1_Brass_-_Polished_0'].geometry}
          material={materials['Brass_-_Polished']}
        />
        <mesh
          geometry={nodes['Hook_2_Brass_-_Polished_0'].geometry}
          material={materials['Brass_-_Polished']}
        />
      </group>
    </group>
  )
}

export default ProjectorScreen
