/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Mário Mendes (https://sketchfab.com/mariomendesdeveloper)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/house-door-8082816a90904e76b45bc6751435412b
title: House Door
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import DoorModelPath from './door.glb'
import { useGLTF } from '@react-three/drei'

type GLTFResult = GLTF & {
  nodes: {
    door_door_0: THREE.Mesh
    door_puller_0: THREE.Mesh
    frame_door_frame_0: THREE.Mesh
  }
  materials: {
    door: THREE.MeshStandardMaterial
    puller: THREE.MeshStandardMaterial
    door_frame: THREE.MeshStandardMaterial
  }
}

const Door = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(DoorModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group scale={4} position={[0, 784, 50]}>
        <group position={[-90.09, -194.36, -7.05]} scale={100}>
          <mesh
            geometry={nodes.door_door_0.geometry}
            material={materials.door}
          />

          <mesh
            geometry={nodes.door_puller_0.geometry}
            material={materials.puller}
          />
        </group>

        <group position={[-7.53, 137.84, -12.68]} scale={[100, 100, 159.88]}>
          <mesh
            geometry={nodes.frame_door_frame_0.geometry}
            material={materials.door_frame}
          />
        </group>
      </group>
    </group>
  )
}

export default Door
