export const COIL_TURNS_COUNT_MIN = 10
export const COIL_TURNS_COUNT_MAX = 1000
export const COIL_TURNS_COUNT_STEP = 50
export const COIL_TURNS_COUNT_DEFAULT = 500

export const COIL_FRAME_WIDTH_MIN = 0.02
export const COIL_FRAME_WIDTH_MAX = 0.2
export const COIL_FRAME_WIDTH_STEP = 0.02
export const COIL_FRAME_WIDTH_DEFAULT = 0.1

export const COIL_FRAME_LENGTH_MIN = 0.02
export const COIL_FRAME_LENGTH_MAX = 0.2
export const COIL_FRAME_LENGTH_STEP = 0.02
export const COIL_FRAME_LENGTH_DEFAULT = 0.1
