export const HELMHOLTZ_COILS_RADIUS_MIN = 10
export const HELMHOLTZ_COILS_RADIUS_MAX = 100
export const HELMHOLTZ_COILS_RADIUS_STEP = 5

export const HELMHOLTZ_COILS_AMPERAGE_MIN = 1
export const HELMHOLTZ_COILS_AMPERAGE_MAX = 10
export const HELMHOLTZ_COILS_AMPERAGE_STEP = 0.5

export const HELMHOLTZ_COILS_TURNS_COUNT_MIN = 1000
export const HELMHOLTZ_COILS_TURNS_COUNT_MAX = 20000
export const HELMHOLTZ_COILS_TURNS_COUNT_STEP = 100
