export const HELMHOLTZ_COILS_RADIUS_MIN = 0.2
export const HELMHOLTZ_COILS_RADIUS_MAX = 0.5
export const HELMHOLTZ_COILS_RADIUS_STEP = 0.01
export const HELMHOLTZ_COILS_RADIUS_DEFAULT = 0.25

export const HELMHOLTZ_COILS_TURNS_COUNT_MIN = 50
export const HELMHOLTZ_COILS_TURNS_COUNT_MAX = 500
export const HELMHOLTZ_COILS_TURNS_COUNT_STEP = 10
export const HELMHOLTZ_COILS_TURNS_COUNT_DEFAULT = 100
