export const MOTOR_ROTATION_FREQUENCY_MIN = 10
export const MOTOR_ROTATION_FREQUENCY_MAX = 100
export const MOTOR_ROTATION_FREQUENCY_STEP = 2
export const MOTOR_ROTATION_FREQUENCY_DEFAULT = 50

export const MOTOR_ROTATION_DIRECTION_DEFAULT: RotationDirection = 'right'
