export const MOTOR_ROTATION_FREQUENCY_MIN = 100
export const MOTOR_ROTATION_FREQUENCY_MAX = 1000

export const MOTOR_ROTATION_FREQUENCY_STEP = 100

export const MOTOR_ROTATION_FREQUENCY_DEFAULT = 800

export const MOTOR_ROTATION_DIRECTION_DEFAULT: RotationDirection = 'right'
