export const OSCILLOSCOPE_CONTRAST_MIN = 0
export const OSCILLOSCOPE_CONTRAST_MAX = 1
export const OSCILLOSCOPE_CONTRAST_STEP = 0.05
export const OSCILLOSCOPE_CONTRAST_DEFAULT = 0.7

export const OSCILLOSCOPE_SCALE_X_MIN = 0.5
export const OSCILLOSCOPE_SCALE_X_MAX = 3
export const OSCILLOSCOPE_SCALE_X_STEP = 0.5
export const OSCILLOSCOPE_SCALE_X_DEFAULT = 1

export const OSCILLOSCOPE_SCALE_Y_MIN = 0.5
export const OSCILLOSCOPE_SCALE_Y_MAX = 3
export const OSCILLOSCOPE_SCALE_Y_STEP = 0.5
export const OSCILLOSCOPE_SCALE_Y_DEFAULT = 1

export const GRID_CELLS_COUNT_IN_QUARTER = 4
