/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Prof Decor Group (https://sketchfab.com/profdecorgroup)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/wallstyl-fl3-nmc-f84da6d64ec947a0b99691c68a10c3e7
title: WALLSTYL FL3 NMC
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import PlinthModelPath from './plinth.glb'
import { useGLTF } from '@react-three/drei'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
}

const Plinth = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(PlinthModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group scale={0.8} position={[38, 44, 0]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  )
}

export default Plinth
