/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Monke (https://sketchfab.com/cosmiccobra)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/conference-chair-9b039bfc7fd04560bf3e8440fdb660da
title: Conference Chair
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import ChairModelPath from './chair.glb'
import { useGLTF } from '@react-three/drei'

type GLTFResult = GLTF & {
  nodes: {
    Conference_Chair_Material002_0: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

const Chair = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(ChairModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1000}>
        <mesh
          geometry={nodes.Conference_Chair_Material002_0.geometry}
          material={materials['Material.002']}
        />
      </group>
    </group>
  )
}

export default Chair
