/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Vince_Crusty (https://sketchfab.com/vince.trust)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ceiling-lamp-fluorescent-tube-baked-b6f971b820df47f0b239d3f94bfb1773
title: Ceiling Lamp / Fluorescent Tube - Baked
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import LampModelPath from './lamp.glb'
import { useGLTF } from '@react-three/drei'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    Baked: THREE.MeshBasicMaterial
  }
}

const Lamp = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(LampModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group scale={630} position={[0, 30, 0]}>
        <group scale={[0.1, 0.06, 0.65]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Baked} />
        </group>
      </group>
    </group>
  )
}

export default Lamp
