/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Spacesea (https://sketchfab.com/-Spacesea-)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/reversible-chalkboard-7c2682ee49404e26b65bca26dd29a9c8
title: Reversible Chalkboard
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'
import BlackboardModelPath from './blackboard.glb'

type GLTFResult = GLTF & {
  nodes: {
    Cube__0: THREE.Mesh
    Cube001__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

const Blackboard = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(BlackboardModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Cube__0.geometry}
              material={materials['Scene_-_Root']}
            />
          </group>

          <group
            position={[0, 700, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Cube001__0.geometry}
              material={materials['Scene_-_Root']}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

export default Blackboard
