/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ChelseaM (https://sketchfab.com/ChelseaM)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/projector-b002e5f720074145a522099542c02f1b
title: Projector
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'
import ProjectorModelPath from './projector.glb'

type GLTFResult = GLTF & {
  nodes: {
    ['Box001_07_-_Default_0']: THREE.Mesh
    ['Box001_02_-_Default_0']: THREE.Mesh
    ['Box002_08_-_Default_0']: THREE.Mesh
    ['Box003_08_-_Default_0']: THREE.Mesh
    ['Box004_08_-_Default_0']: THREE.Mesh
    ['Box005_08_-_Default_0']: THREE.Mesh
    ['Box006_08_-_Default_0']: THREE.Mesh
    ['Cylinder001_01_-_Default_0']: THREE.Mesh
    ['Cylinder001_07_-_Default_0']: THREE.Mesh
  }
  materials: {
    ['07_-_Default']: THREE.MeshStandardMaterial
    ['02_-_Default']: THREE.MeshStandardMaterial
    ['08_-_Default']: THREE.MeshStandardMaterial
    ['01_-_Default']: THREE.MeshStandardMaterial
  }
}

const Projector = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(ProjectorModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group
        position={[-7.4, 62, 8.04]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={4}
      >
        <group position={[0, 3.54, -15.54]} scale={[1, 1, 0.55]}>
          <mesh
            geometry={nodes['Box001_07_-_Default_0'].geometry}
            material={materials['07_-_Default']}
          />
          <mesh
            geometry={nodes['Box001_02_-_Default_0'].geometry}
            material={materials['02_-_Default']}
          />
        </group>
        <group position={[-14.07, -11.47, -15.54]}>
          <mesh
            geometry={nodes['Box002_08_-_Default_0'].geometry}
            material={materials['08_-_Default']}
          />
        </group>
        <group position={[13.44, -11.47, -15.54]}>
          <mesh
            geometry={nodes['Box003_08_-_Default_0'].geometry}
            material={materials['08_-_Default']}
          />
        </group>
        <group position={[-14.07, 19.91, -15.54]}>
          <mesh
            geometry={nodes['Box004_08_-_Default_0'].geometry}
            material={materials['08_-_Default']}
          />
        </group>
        <group position={[13.44, 19.75, -15.54]}>
          <mesh
            geometry={nodes['Box005_08_-_Default_0'].geometry}
            material={materials['08_-_Default']}
          />
        </group>
        <group position={[1.53, 3.37, 3.87]} scale={[1, 1, 3]}>
          <mesh
            geometry={nodes['Box006_08_-_Default_0'].geometry}
            material={materials['08_-_Default']}
          />
        </group>
        <group position={[0.37, -19.2, -5.38]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes['Cylinder001_01_-_Default_0'].geometry}
            material={materials['01_-_Default']}
          />
          <mesh
            geometry={nodes['Cylinder001_07_-_Default_0'].geometry}
            material={materials['07_-_Default']}
          />
        </group>
      </group>
    </group>
  )
}

export default Projector
