/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: chrisnhe (https://sketchfab.com/chrisnhe)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/black-power-socket-8df6e48c3dc64a87acb8eb4f73f283ae
title: Black Power Socket
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'
import PowerSocketModelPath from './powerSocket.glb'

type GLTFResult = GLTF & {
  nodes: {
    Cube_Material001_0: THREE.Mesh
    Sphere_Material002_0: THREE.Mesh
    Torus_Material002_0: THREE.Mesh
    Torus001_Material002_0: THREE.Mesh
    Cube001_Material001_0: THREE.Mesh
    Cube002_Material001_0: THREE.Mesh
    Cube003_Material001_0: THREE.Mesh
    Cube004_Material001_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

const PowerSocket = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(PowerSocketModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group scale={2.8} position={[0, 26, 0]} rotation={[0, Math.PI, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={[10.46, 5.06, 10.46]}>
          <mesh
            geometry={nodes.Cube_Material001_0.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          position={[0, 0, 1.18]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1, 0.39, 1]}
        >
          <mesh
            geometry={nodes.Sphere_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[0, 7.56, -1.39]}
          rotation={[-1.8, Math.PI / 2, 0]}
          scale={[1, 3, 2]}
        >
          <mesh
            geometry={nodes.Torus_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[0.11, -7.51, -1.42]}
          rotation={[-1.34, Math.PI / 2, 0]}
          scale={[1, 3, 2]}
        >
          <mesh
            geometry={nodes.Torus001_Material002_0.geometry}
            material={materials['Material.002']}
          />
        </group>
        <group
          position={[-7.25, -2.18, -0.84]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1, 3, 1]}
        >
          <mesh
            geometry={nodes.Cube001_Material001_0.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          position={[7.06, -2.15, -0.35]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1, 3, 1]}
        >
          <mesh
            geometry={nodes.Cube002_Material001_0.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          position={[-7.27, 2.04, -0.78]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1, 3, 1]}
        >
          <mesh
            geometry={nodes.Cube003_Material001_0.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          position={[7.04, 2.01, -0.27]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1, 3, 1]}
        >
          <mesh
            geometry={nodes.Cube004_Material001_0.geometry}
            material={materials['Material.001']}
          />
        </group>
      </group>
    </group>
  )
}

export default PowerSocket
