/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: charles.cla (https://sketchfab.com/charles.cla)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/sofa-grey-fabric-7f8cca8fe9d8449684b1dfbb410af8c6
title: Sofa grey fabric
*/

import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import SofaModelPath from './sofa.glb'
import { useGLTF } from '@react-three/drei'

type GLTFResult = GLTF & {
  nodes: {
    dessous__0: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshStandardMaterial
  }
}

const Sofa = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF(SofaModelPath) as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={8}>
        <mesh
          geometry={nodes.dessous__0.geometry}
          material={materials['Scene_-_Root']}
        />
      </group>
    </group>
  )
}

export default Sofa
